generator_ckpt: checkpoints/framewise/ar_diffusion.pt
generator_grad:
  model: true
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
generator_task: causal_video
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
mixed_precision: true
seed: 0
wandb_host: https://api.wandb.ai
wandb_key: {your key}
wandb_entity: {your entity}
wandb_project: {your project}
wandb_name: ode
sharding_strategy: hybrid_full
lr: 2.0e-06
beta1: 0.9
beta2: 0.999
data_path: dataset/ODE6KCausal_framewise
batch_size: 1
log_iters: 1000
trainer: ode
gradient_checkpointing: true
num_frame_per_block: 1 
model_kwargs:
  timestep_shift: 5.0
